### ISSUE TITLE
Magento 2.3.1 :: Undefined index: treggo_shipping_module_last_price

### ISSUE THREAD

**Issue by nmarquezdrubu** [treggo/treggo-magento#1]
Buenas!
Al instalar el modulo, despues de un setup:upgrade, nos aparecio este error en el admin de magento:
The XML in file ".../app/code/Treggoapp/Treggoshippingmethod/etc/adminhtml/routes.xml" is invalid:
Element 'config', attribute '{https://www.w3.org/2001/XMLSchema-instance}noNamespaceSchemaLocation': The attribute '{https://www.w3.org/2001/XMLSchema-instance}noNamespaceSchemaLocation' is not allowed.

Esto fue solucionado reemplazando
`<config xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:App/etc/routes.xsd">`

por:
`<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:App/etc/routes.xsd">
`

Por otro lado, despues de registrar el sitio me esta apareciendo el siguiente error en el checkout:
Undefined index: treggo_shipping_module_last_price in .../app/code/Treggoapp/Treggoshippingmethod/Model/Carrier/Shipping.php on line 152

Saludos

**Comment by matiasdamenorockstar** [comment]
Buen día, @nmarquezdrubu 
Esto fue resuelto con el último release. 

Te pedimos por favor que descargues o instales con composer la nueva versión.

Muchas gracias por el reporte.

Saludos,
Matías .-
